### ISSUE TITLE
希望能够定期更新

### ISSUE THREAD

**Issue by smalllqiang** [Delsin-Yu/THBWiki-Markdown#2]

**Comment by Delsin-Yu** [comment]
可以是可以的，但是决定以何种频率来更新是个问题，我不想快速的达到GitHub的存储库的容量上限

**Comment by smalllqiang** [comment]
有更新计划就好, 更新频率您可以另行考量嘛👍

**Comment by Delsin-Yu** [comment]
因为这个仓库基本上是用作冷备份的，我目前的想法可能是以年为单位进行更新吧

**Comment by smalllqiang** [comment]
是这样的, 而且我想如果急用的话其实可以自行用bulider构建最新的(
